version: '2'
services:
  db:
    image: postgres:9.6.2-alpine
  web:
    build: .
    command: ["./wait-for-pg.sh", "--", "python3", "./manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/source
    ports:
      - "8000:8000"
    depends_on:
      - db
